- packages/frontend/package.json
- packages/frontend/src/pages/_app.tsx
- packages/frontend/src/providers/wagmi.tsx
- pnpm-lock.yaml
---
- https://app.asana.com/0/0/1207053421969144
> 🐔 Configure wagmi

- packages/frontend/src/blockchain/abi/auction.ts
---
- https://app.asana.com/0/0/1207071666712218
> 👩‍🚀 Update auction ABI to the latest version

- .github/actions/install-dependencies/action.yml
- .github/workflows/CI.yml
- package.json
---
- https://app.asana.com/0/0/1207053421969164
> 🦀 Run lint in CI

- packages/frontend/src/blockchain/hooks/useAuctionState.ts
- packages/frontend/src/components/common/Separator.tsx
- packages/frontend/src/components/userActious/UserActionSection.tsx
- packages/frontend/src/components/userActious/gitcoin/CheckGitcoinPassword.tsx
- packages/frontend/src/components/userActious/gitcoin/GitcointFlow.tsx
- packages/frontend/src/styles/colors.ts
---
- https://app.asana.com/0/0/1207071811785973
> 🎸 Add Gitcoin flow with first step

- packages/frontend/src/components/userActious/UserActionSection.tsx
- packages/frontend/src/components/userActious/claim/AwaitingResults.tsx
- packages/frontend/src/components/userActious/claim/ClaimingClosed.tsx
- packages/frontend/src/components/userActious/claim/ResultsAwaiting.tsx
Added AwaitingResults and ClaimingClosed states
> 🧱 Add claiming static views

- packages/frontend/src/blockchain/hooks/useBidWinType.ts
- packages/frontend/src/blockchain/hooks/useUserBid.ts
- packages/frontend/src/types/bid.ts
---
- https://app.asana.com/0/0/1207131241780060
> ℹ️ Add WinType to useUserBid

- packages/frontend/src/components/bids/BidsColumns.tsx
- packages/frontend/src/components/bids/BidsListEntry.tsx
- packages/frontend/src/components/bids/allBids/AllBids.tsx
- packages/frontend/src/components/bids/allBids/BidsSubList.tsx
- packages/frontend/src/components/bids/allBids/GoldenTicketWinner.tsx
- packages/frontend/src/components/bids/allBids/Header.tsx
- packages/frontend/src/components/bids/bidsShortList/BidsShortListSection.tsx
- packages/frontend/src/components/buttons/BackButton.tsx
- packages/frontend/src/components/buttons/Button.tsx
- packages/frontend/src/components/common/Separator.tsx
- packages/frontend/src/components/form/Input.tsx
- packages/frontend/src/components/form/SearchInput.tsx
- packages/frontend/src/components/info/Accordion.tsx
- packages/frontend/src/components/info/Header.tsx
- packages/frontend/src/components/info/Rules.tsx
- packages/frontend/src/components/info/TimeLeft.tsx
- packages/frontend/src/components/info/VoucherTimeLeft.tsx
- packages/frontend/src/components/stepper/Stepper.tsx
- packages/frontend/src/components/tooltip/TooltipButton.tsx
- packages/frontend/src/components/tooltip/TooltipLink.tsx
- packages/frontend/src/components/topBar/AccountDetailModal.tsx
- packages/frontend/src/components/topBar/Modal.tsx
- packages/frontend/src/components/userActious/gitcoin/InsufficientUserScore.tsx
- packages/frontend/src/components/userActious/gitcoin/MissingGitcoinPassport.tsx
- packages/frontend/src/pages/bids.tsx
- packages/frontend/src/styles/GobalStyles.tsx
- packages/frontend/src/styles/colors.ts
---
- https://app.asana.com/0/0/1207159475162283
- https://app.asana.com/0/0/1207159475162282
> 💅🏻 Update colors

- packages/frontend/package.json
- packages/frontend/src/blockchain/hooks/useUserBid.ts
- packages/frontend/src/components/notifications/ErrorNotifications.tsx
- packages/frontend/src/components/notifications/NotificationToast.tsx
- packages/frontend/src/components/userActious/UserActionSection.tsx
- packages/frontend/src/components/userActious/claim/ClaimVoucherSection.tsx
- packages/frontend/src/components/userActious/claim/ClaimingFlow.tsx
- packages/frontend/src/components/userActious/claim/NoBidding.tsx
- packages/frontend/src/components/userActious/claim/VoucherForm.tsx
- packages/frontend/src/components/userActious/claim/VoucherTimeLeft.tsx
- packages/frontend/src/components/userActious/claim/WinBidFlow.tsx
- packages/frontend/src/components/userActious/claim/WinBidForm.tsx
- packages/frontend/src/components/userActious/claim/WinForm.tsx
- packages/frontend/src/types/bid.ts
- packages/frontend/src/types/winType.ts
- pnpm-lock.yaml
---
- https://app.asana.com/0/0/1207131241780062
> 🏧 Add claiming flow components

- packages/frontend/src/components/bids/allBids/Header.tsx
- packages/frontend/src/components/form/Form.tsx
- packages/frontend/src/components/info/Rules.tsx
- packages/frontend/src/components/topBar/AccountDetailModal.tsx
- packages/frontend/src/styles/GobalStyles.tsx
---
- https://app.asana.com/0/0/1207159475162285
> 🖌️ Update typography

- packages/frontend/src/blockchain/hooks/useMinimumIncrement.ts
- packages/frontend/src/blockchain/hooks/useReadAuctionParams.ts
- packages/frontend/src/components/userActious/bid/BidFlow.tsx
- packages/frontend/src/components/userActious/bid/BumpBid/BumpBidFlow.tsx
- packages/frontend/src/components/userActious/bid/BumpBid/BumpBidForm.tsx
- packages/frontend/src/components/userActious/bid/BumpBid/getPositionAfterBump.ts
- packages/frontend/src/components/userActious/bid/BumpBid/useBumpBid.ts
---
- https://app.asana.com/0/0/1207071811980069
> 🦑 Add Bump Bid flow

- packages/frontend/src/components/notifications/ErrorNotifications.tsx
- packages/frontend/src/components/notifications/NotificationToast.tsx
- packages/frontend/src/components/userActious/claim/ClaimVoucherSection.tsx
---
- https://app.asana.com/0/0/1207131241780065
> 🫴 Handle voucher claiming

- packages/frontend/src/components/form/Form.tsx
- packages/frontend/src/components/form/ReviewForm.tsx
- packages/frontend/src/components/icons/EtherIcon.tsx
- packages/frontend/src/components/stepper/Stepper.tsx
- packages/frontend/src/components/stepper/TransactionStepper.tsx
- packages/frontend/src/components/userActious/BidAwaiting.tsx
- packages/frontend/src/components/userActious/bid/BumpBid/BumpBidForm.tsx
- packages/frontend/src/components/userActious/bid/PlaceBid/PlaceBidForm.tsx
- packages/frontend/src/components/userActious/claim/AwaitingResults.tsx
- packages/frontend/src/components/userActious/claim/ClaimVoucherSection.tsx
- packages/frontend/src/components/userActious/claim/VoucherTimeLeft.tsx
- packages/frontend/src/components/userActious/claim/WinBidForm.tsx
---
- https://app.asana.com/0/0/1207159475162280
- https://app.asana.com/0/0/1207159475162291
> 🎲 Update action section

- packages/frontend/src/components/userActious/gitcoin/CheckGitcoinPassport.tsx
---
- https://app.asana.com/0/0/1207276801438368
> 🔀 Handle create passport button

- packages/frontend/src/components/bids/bidsShortList/BidsShortList.tsx
---
- https://app.asana.com/0/0/1207297720094026
> 🔦 Highlight auction bid only once

- packages/frontend/src/pages/bids.tsx
> fix: metadata in frame head

- packages/frontend/src/components/auction/Auction.tsx
- packages/frontend/src/components/bids/BidsColumns.tsx
- packages/frontend/src/components/bids/bidsShortList/BidsShortListSection.tsx
- packages/frontend/src/components/footer/Footer.tsx
- packages/frontend/src/components/form/Form.tsx
- packages/frontend/src/components/info/Accordion.tsx
- packages/frontend/src/components/info/Header.tsx
- packages/frontend/src/components/info/TimeLeft.tsx
- packages/frontend/src/components/layout/Layout.tsx
- packages/frontend/src/components/topBar/TopBar.tsx
- packages/frontend/src/components/userActious/UserActionSection.tsx
- packages/frontend/src/components/userActious/bid/BumpBid/BumpBidForm.tsx
- packages/frontend/src/components/userActious/bid/PlaceBid/PlaceBidForm.tsx
- packages/frontend/src/components/userActious/gitcoin/CheckGitcoinPassport.tsx
- packages/frontend/src/hooks/useResponsiveHelper.ts
- packages/frontend/src/pages/index.tsx
- packages/frontend/src/styles/mediaQueries.ts
Mobile layout + media queries for components on the main page.
---
- https://app.asana.com/0/0/1207494231957704
> ☎️ Add mobile layout

- packages/frontend/src/components/auction/AuctionTransaction.tsx
- packages/frontend/src/components/auction/TransactionSuccess/TransactionSuccess.tsx
- packages/frontend/src/components/buttons/ConnectWalletButton.tsx
- packages/frontend/src/components/form/Form.tsx
- packages/frontend/src/components/info/VoucherTimeLeft.tsx
- packages/frontend/src/components/stepper/TransactionStepper.tsx
- packages/frontend/src/components/userActious/BidAwaiting.tsx
- packages/frontend/src/components/userActious/claim/AwaitingResults.tsx
- packages/frontend/src/components/userActious/claim/ClaimingClosed.tsx
- packages/frontend/src/components/userActious/claim/VoucherTimeLeft.tsx
- packages/frontend/src/components/userActious/claim/WinBidForm.tsx
- packages/frontend/src/components/userActious/claim/WinForm.tsx
- packages/frontend/src/components/userActious/gitcoin/CheckGitcoinPassport.tsx
- packages/frontend/src/components/userActious/gitcoin/CheckingGitcoinScore.tsx
- packages/frontend/src/components/userActious/gitcoin/InsufficientUserScore.tsx
- packages/frontend/src/components/userActious/gitcoin/MissingGitcoinPassport.tsx
- packages/frontend/src/components/userActious/gitcoin/SufficientUserScore.tsx
---
- https://app.asana.com/0/0/1207504200653681
> 👩🏻‍🎤 Add mobile styles for user action section

- packages/frontend/src/components/userActious/claim/VoucherForm.tsx
- packages/frontend/src/components/userActious/claim/WinForm.tsx
---
- https://app.asana.com/0/0/1207524798486563
> 🎉 Add mobile styles for win flow

- packages/frontend/src/components/topBar/Modal.tsx
- packages/frontend/src/styles/mediaQueries.ts
---
- https://app.asana.com/0/0/1207522308756645
> 🥅 Add mobile styles for modal

- packages/frontend/src/blockchain/auctionAddresses.ts
---
- https://app.asana.com/0/0/1207301387851885
> 🏆 Update auction address on Mainnet

- packages/contracts/deployments.json
- packages/contracts/hardhat.config.ts
- packages/contracts/package.json
- packages/contracts/scripts/deployAuctionRaffle.ts
- packages/contracts/scripts/deploymentConfig.ts
- packages/frontend/src/blockchain/auctionAddresses.ts
~~https://arbiscan.io/address/0xe2ef0cb2a3ccf8107d28f01dc721055225d5feda~~
https://arbiscan.io/address/0x1E7aC276CBdae55689Df1d99108d69Fff444cB88
> Deploy to arb1

- packages/frontend/src/constants/shareText.ts
---
- https://app.asana.com/0/0/1207593977329850
> 💌 Update share message
